add body emphasized var
compound-finance/compound-styles pull request #7
Opened 2023-05-01 22:41 UTC by alysiawu

add body emphasized var as font weight 600

2023-05-01 22:57 UTC, torreyatcitty commented
Do you have a link to the updated design guide from Josiah were these have been defined?

I think the intention was to only update the styles for L4, where this is going to update for everything which is not what we want I don't think

2023-05-01 23:17 UTC, alysiawu commented
Since I notice the heading font weight emphasized across all levels are the same weight, so I deduce for body should be the same... but checking w Josiah now..  ```$heading-font-weight--emphasized--L0: 600;
$heading-font-weight--emphasized--L1: 600;
$heading-font-weight--emphasized--L2: 600;
$heading-font-weight--emphasized--L3: 600;
$heading-font-weight--emphasized--L4: 600; ```

2023-05-03 23:43 UTC, alysiawu commented on scss/base/_typography.scss
> +  --body-font-weight--emphasized: #{$body-font-weight--emphasized--L1};
notice --header font weight was using the L1 variable, so using the L1 for body as well

2023-05-04 04:45 UTC, torreyatcitty approved these changes
Yup this makes sense to me. LGTM.

@mykelp would you like to also take a quick look over to confirm it matches the original intention?

2023-05-04 15:18 UTC, mykelp requested changes
This isn't quite correct. Left snippets on how to update

2023-05-04 15:18 UTC, mykelp commented on scss/base/_typography.scss
> +
This isn't quite correct. you need to add all the variables

```scss
$body-font-family--emphasized--L0: "Haas Grot Text R";
$body-font-family--emphasized--L1: "Haas Grot Text R";
$body-font-family--emphasized--L2: "Haas Grot Text R";
$body-font-family--emphasized--L3: "Haas Grot Text R";
$body-font-family--emphasized--L4: "Haas Grot Text R";

$body-font-size--emphasized--L0: 0rem;
$body-font-size--emphasized--L1: 1.25rem;
$body-font-size--emphasized--L2: 1.0625rem;
$body-font-size--emphasized--L3: 0.9375rem;
$body-font-size--emphasized--L4: 0.8125rem;

$body-font-weight--emphasized--L0: normal;
$body-font-weight--emphasized--L1: 500;
$body-font-weight--emphasized--L2: 500;
$body-font-weight--emphasized--L3: 500;
$body-font-weight--emphasized--L4: 500;

$body-line-height--emphasized--L0: 0rem;
$body-line-height--emphasized--L1: 1.75rem;
$body-line-height--emphasized--L2: 1.5rem;
$body-line-height--emphasized--L3: 1.25rem;
$body-line-height--emphasized--L4: 1.125rem;

$body-paragraph--emphasized--L0: 0rem;
$body-paragraph--emphasized--L1: 1rem;
$body-paragraph--emphasized--L2: 0.75rem;
$body-paragraph--emphasized--L3: 0.5rem;
$body-paragraph--emphasized--L4: 0.5rem;
```

2023-05-04 15:18 UTC, mykelp commented on scss/base/_typography.scss
> +
This was just copied, but we'd need to fill those out with the correct values for each level

2023-05-04 15:18 UTC, mykelp commented on scss/base/_typography.scss
> +  --body-font-weight--emphasized: #{$body-font-weight--emphasized--L1};
same as above this needs to have the full list of variables set

```scss
  --body-font-family--emphasized: #{$body-font-family--emphasized--L1};
  --body-font-size--emphasized: #{$body-font-size--emphasized--L1};
  --body-font-weight--emphasized: #{$body-font-weight--emphasized--L1};
  --body-line-height--emphasized: #{$body-line-height--emphasized--L1};
  --body-paragraph--emphasized: #{$body-paragraph--emphasized--L1};

```

2023-05-04 15:18 UTC, mykelp commented on scss/base/_typography.scss
> +  --body-font-weight--emphasized: #{$body-font-weight--emphasized--L0};
ditto: same as above

2023-05-04 15:18 UTC, mykelp commented on scss/base/_typography.scss
> +  --body-font-weight--emphasized: #{$body-font-weight--emphasized--L1};
same as above

2023-05-04 15:19 UTC, mykelp commented on scss/base/_typography.scss
> +  --body-font-weight--emphasized: #{$body-font-weight--emphasized--L2};
same as above

2023-05-04 15:19 UTC, mykelp commented on scss/base/_typography.scss
> +  --body-font-weight--emphasized: #{$body-font-weight--emphasized--L3};
same as above

2023-05-04 15:19 UTC, mykelp commented on scss/base/_typography.scss
> +  --body-font-weight--emphasized: #{$body-font-weight--emphasized--L4};
same as above

2023-05-04 15:20 UTC, mykelp commented on scss/base/_typography.scss
> +    font-weight: var(--body-font-weight--emphasized);
this needs all the values set 

```scss
    font-family: var(--body-font-family--emphasized);
    font-size: var(--body-font-size--emphasized);
    font-weight: var(--body-font-weight--emphasized);
    line-height: var(--body-line-height--emphasized);
```

2023-05-04 15:22 UTC, mykelp commented
Ok I realize the issue now...we should revert all these changes. There was a name change in the CDS from `body--link` to `body--emphasized`. So all that's required is to change the `--link` to `--emphasized`. Then check in webb3 for all occurrences to `body--link` and update to `body--emphasized`

2023-05-04 17:23 UTC, torreyatcitty commented
That sucks. @alysiawu let's hold off on finishing this until trx-history is out. Originally it was fine to update `body--emphasized` across the board but updating `body--link` to become `body--emphasized` as @mykelp says touches more views across the app that I would like us to do in a separate build for design to verify all the cases to make sure is fine.

Also, we should confirm with design that this rename was indeed the case with Josiah because I also didn't think this was the case reading the discord messages. I think we should have better versioning of the CDS in Figma and better tickets being opened by design for things we need to change in the CDS where we don't have to be the ones guessing what exactly was changed from memory and looking at the whole CDS.

2023-05-04 17:55 UTC, closed without merging